apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: alertmanager-vs
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        exact: /alertmanager
    - uri:
        prefix: /alertmanager/
    rewrite:
      uri: "/"
    route:
    - destination:
        host: prometheus-alertmanager.default.svc.cluster.local
        port:
          number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: alertmanager-dr
  namespace: default
spec:
  host: prometheus-alertmanager.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE 
---